import type { Metadata } from "next";
import localFont from 'next/font/local'
import { Outfit, Righteous } from "next/font/google";
import AppShell from "@/components/shared/AppShell";
import "./globals.css";



const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});
const header = Righteous({
  variable: "--font-header",
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${outfit.variable}  ${header.variable} h-full antialiased`}
    >
      <body className=" h-svh">
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
