import type { Metadata } from "next";
import localFont from 'next/font/local'
import { Outfit } from "next/font/google";
import "./globals.css";


const header = localFont({
  variable: "--font-header",
  src: './fonts/heading.woff2',
  weight: '400',
  style: 'normal',
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${header.variable} h-full antialiased`}
    >
      <body className="min-h-full font-outfit flex flex-col">{children}</body>
    </html>
  );
}
